---
name: docker

"on":
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  download:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Cache mods
        id: cache
        uses: actions/cache@v3
        with:
          path: overlay/usr/share/minecraft/mods/
          key: mods-${{ hashFiles('client/manifest.json') }}

      - name: Download mods
        id: mods
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker://webhippie/cursecli:1.1.1
        env:
          CURSECLI_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        with:
          entrypoint: cursecli
          args: manifest --manifest client/manifest.json download mods --path overlay/usr/share/minecraft/mods/

  docker:
    runs-on: ubuntu-20.04
    needs: download

    strategy:
      matrix:
        include:
          - platform: linux/amd64
            arch: amd64
          - platform: linux/arm64
            arch: arm64

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Cache mods
        id: cache
        uses: actions/cache@v3
        with:
          path: overlay/usr/share/minecraft/mods/
          key: mods-${{ hashFiles('client/manifest.json') }}

      - name: Download mods
        id: mods
        if: steps.cache.outputs.cache-hit != 'true'
        uses: docker://webhippie/cursecli:1.1.1
        env:
          CURSECLI_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
        with:
          entrypoint: cursecli
          args: manifest --manifest client/manifest.json download mods --path overlay/usr/share/minecraft/mods/

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            crafthippie/owntech
            quay.io/crafthippie/owntech
          labels: |
            org.opencontainers.image.vendor=Crafthippie
            maintainer=Thomas Boerger <thomas@webhippie.de>
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            suffix=-${{ matrix.arch }}

      - name: Setup qemu
        id: qemu
        uses: docker/setup-qemu-action@v2

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Hub login
        id: login1
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Quay login
        id: login2
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Build image
        id: publish
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: docker/Dockerfile.${{ matrix.arch }}
          platforms: ${{ matrix.platform }}
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

  manifest:
    runs-on: ubuntu-20.04
    needs: docker

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v3

      - name: Hub tags
        id: hubTags
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: crafthippie/owntech
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Hub manifest
        id: hub
        if: github.event_name != 'pull_request'
        uses: actionhippie/manifest@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64
          template: crafthippie/owntech:VERSION-ARCH
          target: ${{ steps.hubTags.outputs.tags }}
          ignore_missing: true

      - name: Quay tags
        id: quayTags
        uses: docker/metadata-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: quay.io/crafthippie/owntech
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Quay manifest
        id: quay
        if: github.event_name != 'pull_request'
        uses: actionhippie/manifest@v1
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          platforms: linux/amd64,linux/arm64
          template: quay.io/crafthippie/owntech:VERSION-ARCH
          target: ${{ steps.quayTags.outputs.tags }}
          ignore_missing: true

  readme:
    runs-on: ubuntu-20.04
    needs: docker

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Hub readme
        id: hub
        if: github.event_name != 'pull_request'
        uses: actionhippie/pushrm@v1
        with:
          provider: dockerhub
          target: crafthippie/owntech
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          description: ownTech
          readme: README.md

      - name: Quay readme
        id: quay
        if: github.event_name != 'pull_request'
        uses: actionhippie/pushrm@v1
        with:
          provider: quay
          target: quay.io/crafthippie/owntech
          apikey: ${{ secrets.QUAY_APIKEY }}
          readme: README.md

...
